# Data Exploration of Relationship Between Unanet and CIPs

In [2]:
import pandas as pd

In [4]:
cip = pd.read_json('../data/information.json')
unanet = pd.read_csv('../data/unanet.csv')

In [6]:
cip.head(5)

,Name,Location,Publication Date,Closing Date,Solicitation Number
0,B26-02 - The Ranch Events Complex - Fence Inst...,Colorado,03/31/2026,04/15/2026 02:00 PM MDT,B26-02
1,P26-08 - Hotel P3 - The Ranch,Colorado,03/27/2026,04/27/2026 02:00 PM MDT,P26-08
2,P26-06 - Home Ignition Zone (HIZ) Wildfire Mit...,Colorado,03/17/2026,04/15/2026 02:00 PM MDT,P26-06
3,P26-10 - Geotechnical Consulting and Material ...,Colorado,03/16/2026,04/14/2026 02:00 PM MDT,P26-10
4,D-RFQ - Department's RFQs are posted at www.la...,Colorado,06/11/2024,12/31/2026 02:00 PM MST,D-RFQ

In [7]:
unanet.head(5)

,Lead Name,Stage,Status,Score,City,State,Notes,Next Action,Client,Created By,...,Secondary Categories,Divisions,Studios,Client Type,Office Division,Lead Source,Estimated Size,Estimated Unit Size,Solicitation Number,NAICS Code(s)
0,Evans Freedom Gateway,Unassigned,Open,(1) Unlikely,Loveland,Colorado,NaN,Start proposal for this - February/March Kick-...,NaN,Joe Berlin,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Dillon Amphitheater Restroom Remodel,Assigned,Open,(3) Likely,Dillon,Colorado,NaN,Putting together a proposal for Ryan,JHL Constructors,Jordan Lockner,...,Bathrooms,NaN,NaN,Public,NaN,NaN,NaN,NaN,NaN,NaN
2,Weld County Administration,Unassigned,Open,(2) Meh,Greeley,Colorado,Need to create renderings and set up a meeting...,Riley Johnson providing schematics - Jeff to s...,Weld County,Jordan Lockner,...,NaN,NaN,NaN,Public,NaN,NaN,425000.0,NaN,NaN,NaN
3,Bond Election - Montrose CO School District _ ...,Unassigned,Open,(1) Unlikely,Montrose,Colorado,Note: Review November ballot results when tick...,Follow Up with Riley at Dynamic to make introd...,NaN,Erica Sayers,...,Classrooms Food Service Entry Vestibule Securi...,NaN,NaN,NaN,NaN,CIP,NaN,NaN,CIP ID # 93649,NaN
4,Denver TF - 16th Street retail,Unassigned,Open,(2) Meh,Denver,Colorado,NaN,Jordan followed up week of 12/20 - not update,NaN,Jordan Lockner,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
print('Number of Rows CIP:', len(cip))
print('Number of Rows Unanet:', len(unanet))

Number of Rows CIP: 5
Number of Rows Unanet: 50